# Generated by Django 5.1.7 on 2025-06-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_quiz_description_question_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together=set(),
        ),
    ]
